#
# This script is used to generate Python tests.
#
# The output generated by each test can be seen at:
#
# https://github.com/ialbert/bio/tree/master/test/data
#

# Stop on errors.
set -uex

# Fetch the accession, rename the data and change the sequence id.
bio fetch NC_045512 KM233118 > genome.gb
