#
# This script is used to generate Python tests.
#
# The output generated by each test can be seen at:
#
# https://github.com/ialbert/bio/tree/master/test/data
#

# Stop on errors.
set -uex

# Fetch the accession, rename the data and change the sequence id.
bio fetch NC_045512 MN996532 > genomes.gb

# Convert genbank files to FASTA
bio convert genomes.gb  --fasta > genomes.fa

# Convert genbank files to GFF
bio convert genomes.gb  --gff > genomes.gff
