# Generated by Django 3.1.1 on 2020-09-14 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('definition', models.TextField(max_length=100000)),
                ('accession', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=256)),
                ('dblink', models.CharField(max_length=256)),
                ('keywords', models.CharField(max_length=256)),
                ('organism', models.TextField(max_length=100000)),
                ('origin', models.FilePathField()),
                ('comment', models.TextField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('gene', models.CharField(max_length=256)),
                ('locus_tag', models.CharField(max_length=256)),
                ('ribosomal_slippage', models.BooleanField(default=False)),
                ('note', models.TextField(max_length=100000)),
                ('codon_start', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=256)),
                ('protein_id', models.CharField(max_length=256)),
                ('db_xref', models.CharField(max_length=256)),
                ('inference', models.CharField(max_length=256)),
                ('function', models.CharField(max_length=256)),
                ('bound_moiety', models.CharField(max_length=256)),
                ('experiment', models.CharField(max_length=256)),
                ('translation', models.CharField(max_length=256)),
                ('EC_number', models.CharField(max_length=256)),
                ('direction', models.CharField(max_length=256)),
                ('operon', models.CharField(max_length=256)),
                ('number', models.IntegerField()),
                ('clone', models.BooleanField(default=False)),
                ('anticodon', models.CharField(max_length=256)),
                ('rpt_family', models.CharField(max_length=256)),
                ('rpt_type', models.CharField(max_length=256)),
                ('rpt_unit_seq', models.CharField(max_length=256)),
                ('regulatory_class', models.CharField(max_length=256)),
                ('organism', models.CharField(max_length=256)),
                ('mol_type', models.CharField(max_length=256)),
                ('ecotype', models.CharField(max_length=256)),
                ('strain', models.CharField(max_length=256)),
                ('chromosome', models.IntegerField()),
                ('map', models.CharField(max_length=256)),
                ('lab_host', models.CharField(max_length=256)),
                ('dev_stage', models.CharField(max_length=256)),
                ('focus', models.BooleanField(default=False)),
                ('rearranged', models.BooleanField(default=False)),
                ('cell_line', models.CharField(max_length=256)),
                ('cell_type', models.CharField(max_length=256)),
                ('locus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.locus')),
            ],
        ),
    ]
